import { Equipment } from '@/types'

export const equipmentList: Equipment[] = [
  {
    id: 'road-roller',
    name: 'Road Roller (2-Ton Double Drum)',
    slug: 'road-roller',
    category: 'Compaction',
    description: 'Heavy-duty road roller for compaction of asphalt, gravel, and soil. Ideal for road construction and site preparation.',
    specs: {
      model: 'XYC-2T',
      capacity: '2 Ton',
      power: 'Diesel 15HP',
      weight: '2000kg',
    },
    unitsTotal: 1,
    unitsAvailable: 1,
    pricePerHour: 1200,
    pricePerDay: 8500,
    image: 'https://images.unsplash.com/photo-1621922218783-9d3d05eb17f5?w=600',
    status: 'available',
    features: ['Double Drum', 'Vibratory', 'Reversible', 'Operator Included'],
  },
  {
    id: 'concrete-vibrator',
    name: 'Concrete Vibrator / Poker',
    slug: 'concrete-vibrator',
    category: 'Concrete',
    description: 'High-frequency concrete vibrator for efficient consolidation of fresh concrete. Removes air bubbles for stronger concrete.',
    specs: {
      model: 'VC-50',
      capacity: '50mm diameter',
      power: 'Electric 2.2HP',
    },
    unitsTotal: 1,
    unitsAvailable: 1,
    pricePerHour: 250,
    pricePerDay: 1800,
    image: 'https://images.unsplash.com/photo-1590846083694-23c37d8b3bee?w=600',
    status: 'available',
    features: ['High Frequency', 'Portable', 'Flexible Shaft'],
  },
  {
    id: 'concrete-mixer',
    name: 'Concrete Mixer (350L)',
    slug: 'concrete-mixer',
    category: 'Concrete',
    description: '350-liter capacity concrete mixer for mixing cement, sand, gravel, and water. Suitable for small to medium construction projects.',
    specs: {
      model: 'CM-350',
      capacity: '350 Liters',
      power: 'Electric 3HP',
    },
    unitsTotal: 2,
    unitsAvailable: 2,
    pricePerHour: 600,
    pricePerDay: 4500,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',
    status: 'available',
    features: ['350L Capacity', 'Reversible Drum', 'Hydraulic Tip'],
  },
  {
    id: 'skip-hoist',
    name: 'Skip Hoist (Builder\'s Hoist)',
    slug: 'skip-hoist',
    category: 'Lifting',
    description: 'Material elevator for lifting construction materials to upper floors. Essential for multi-story building projects.',
    specs: {
      model: 'SH-500',
      capacity: '500kg',
      power: 'Diesel 10HP',
      height: '50m max',
    },
    unitsTotal: 1,
    unitsAvailable: 1,
    pricePerHour: 850,
    pricePerDay: 6000,
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600',
    status: 'available',
    features: ['500kg Capacity', '50m Max Height', 'Safety Brake'],
  },
  {
    id: 'water-pump',
    name: 'Water Pump (3" Petrol)',
    slug: 'water-pump',
    category: 'Pumping',
    description: '3-inch petrol water pump for dewatering construction sites, drainage, and water transfer applications.',
    specs: {
      model: 'WP-3P',
      capacity: '3 inch',
      power: 'Petrol 5HP',
      flow: '600 L/min',
    },
    unitsTotal: 1,
    unitsAvailable: 1,
    pricePerHour: 300,
    pricePerDay: 2200,
    image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=600',
    status: 'available',
    features: ['3-inch Suction', 'Self-Priming', 'Portable'],
  },
  {
    id: 'shovel',
    name: 'Shovel',
    slug: 'shovel',
    category: 'Tools',
    description: 'Durable construction shovels for excavation, trenching, and material handling. Available in bulk.',
    specs: {
      size: 'Standard',
      material: 'Steel with wooden handle',
    },
    unitsTotal: 10,
    unitsAvailable: 10,
    pricePerHour: 25,
    pricePerDay: 200,
    image: 'https://images.unsplash.com/photo-1595846519845-68e298c2edd8?w=600',
    status: 'available',
    features: ['Steel Blade', 'Wooden Handle', 'Various Sizes'],
  },
  {
    id: 'bucket',
    name: 'Bucket',
    slug: 'bucket',
    category: 'Tools',
    description: 'Heavy-duty construction buckets for material handling, mixing, and transport. Available in bulk.',
    specs: {
      capacity: '20 Liters',
      material: ' Galvanized Steel',
    },
    unitsTotal: 10,
    unitsAvailable: 10,
    pricePerHour: 15,
    pricePerDay: 100,
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=600',
    status: 'available',
    features: ['20L Capacity', 'Galvanized', 'Reinforced Handle'],
  },
]

export const categories = ['All', 'Compaction', 'Concrete', 'Lifting', 'Pumping', 'Tools']